config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :lists do
    resources :tasks
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  has_many :user_lists
  has_many :users, through: :user_lists

  validates_presence_of :name, uniqueness: true

  accepts_nested_attributes_for :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

     devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :user_lists
  has_many :lists, through: :user_lists

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end      
  end
end

app/models/user_list.rb
class UserList < ActiveRecord::Base
  belongs_to :user
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  #before_action :require_login

  def index
    @list = List.new
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @task = Task.new
  end

  def new 
    @list = List.new
    @list.tasks.build
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @task = Task.find_by(params[:id])
    @task.destroy
    redirect_to @list
  end

  private

  def list_params
    params.require(:list).permit(:name, tasks_attributes: [:name, :status])
  end

  def require_login
    return head(:forbidden) unless session.include? :user_id    
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def index
    @task = Task.all
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.build(task_params)
    @task.save
    redirect_to @list
  end
  
  def edit
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to list_path(@task.list)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to list_path(@task.list)
  end

  private
  
  def task_params
    params.require(:task).permit(:name, :status)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user
    else
      redirect_to new_user_registration_path
    end       
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Group Task Manager</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>
<nav class="navbar navbar-default navbar-static-top" style="background: #F1F1F1">
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      Menu
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <li class="dropdown-header"><u>Lists</u></li>
        <li><%= link_to "Create List", new_list_path %></li>
        
        <li><%= link_to "View Lists", lists_path %></li>
        <li role="separator" class="divider"></li>
      <li><%= link_to "Login", new_user_session_path %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
    </ul>
  </div>
  <ul><ul><h1 style="float: auto; padding: -100px;">Group Task Manager</h1></ul></ul>
</nav>

<ul>
  <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
  <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
  <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
</ul>

<%= yield %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>  

</body>
</html>

app/views/lists/_list.html.erb
<%= form_for(@list) do |list_form| %>
   <ul> <h4>List Name: <%= list_form.text_field :name, placeholder: "Create a List" %></h4>
      <%= list_form.fields_for :tasks, @list.tasks do |task_field| %>
        <h4>Task Name: <%= task_field.text_field :name, placeholder: "Create a Task" %></h4>
      <% end %>
      <h4><%= list_form.submit %></h4>
    <% end %>
  </ul>
</ul>

app/views/lists/edit.html.erb
<h2>Edit Your List:</h2>
<h3><%= @list.name %></h3>

<%= render 'list' %>

app/views/lists/index.html.erb
<% if user_signed_in? %> 
  <h2><ul> Welcome, <%= current_user.email if !current_user.nil? %></ul></h2>
    
    <ul><%= form_for(@list) do |f| %>
      <%= f.text_field :name, placeholder: 'i.e. Grocery' %>
      <%= f.submit %>
      <% end %>
    </ul>
    
    <ul><h3>Here are all lists:</h3>
      <% @lists.each do |list| %>
        <input class="toggle-all" type="checkbox">
        <label for="toggle-all">Mark as complete:</label>
        <ul><h4> &#62; <%= link_to list.name, list %></h4></ul>
      <% end %>
    </ul>
<% else %>
  <h2><ul> Welcome!</ul></h2>
  <ul><h3>This is a group task manager application for users to keep track of their daily functions.</h3></ul>
  <ul><h3>To get started, click the menu icon and click "Sign Up" - or "Login" if you've already made an account.</h3></ul>
  <ul><h4>(You may also be given the option to sign in with you Github info if you'd prefer.)</h4></ul>
<% end %>


 

 
 

app/views/lists/new.html.erb
<ul><h2>Create A New List with a Task</h2>

<%= render 'list' %>

app/views/lists/show.html.erb
<ul>
  <h3><%= @list.name %></h3>
    <%= form_for([@list, Task.new]) do |f| %>
      <%= f.text_field :name, placeholder: "Create a task" %>
      <%= f. submit %>
    <% end %>


  <ul>
    <%= render @list.tasks %>
    <% if !@list.tasks.nil? %>
    <%= button_to "Task Complete", lists_path, :method => "destroy", :class => "destroy" %>
    <% else %>
    <h4>There are currently no tasks associated to this list!</h4>
    <% end %>
  </ul>
</ul>

app/views/tasks/_task.html.erb
<label>
  <%= task.name %>
</label>

app/views/tasks/index.html.erb
<!-- when a user clicks to view tasks, it links to 'tasks/index' to view all tasks with their associated lists -->

<h2>Here are all tasks:</h3>
<% @task.each do |task| %>
  <h3>
    <ul> 
      > <%= task.name %> 
      <ul>
        <h5>
          <%= button_to "Task Complete?", list_task_path(task.list, task), :method => "delete", :class => "destroy" %>
        </h5>
      </ul> 
    </ul>
  </h3>
  
  <% end %>

app/views/tasks/new.html.erb
<!-- when a user clicks to create a new task, routes to 'tasks/new' -->

app/views/users/login.html.erb
<!-- when a user logs in to their existing account, routes to 'users/login' -->